declare module '*.css'
declare module '*.png'
declare module '*.jpg'
declare module '*.jpeg'
declare module '*.gif'
declare module '*.svg'
declare module '*.webp'
declare module '*.ico'
declare module '*.mp4'
declare module '*.webm'
declare module '*.mp3'
declare module '*.wav'

declare const __APP_MODE__: 'development' | 'production'