name: Basic TypeScript validation

on:
  workflow_call:
    inputs:
      operating-system:
        description: "Optional input to set a list of operating systems which the workflow uses. Defaults to ['ubuntu-latest', 'windows-latest', 'macos-latest'] if not set"
        required: false
        type: string
        default: 'ubuntu-latest'
      node-version-file:
        description: "Optional input to set the version of Node.js used to build the project. The input syntax corresponds to the setup-node's format as of v4.2.0"
        required: false
        type: string
        default: '.nvmrc'
      node-caching:
        description: "Optional input to set up caching for the setup-node action. The input syntax corresponds to the setup-node's format as of v4.2.0. Set to an empty string if caching isn't needed"
        required: false
        type: string
        default: 'pnpm'
      environment:
        description: 'Optional input to set the environment for the workflow. Defaults to `github.env.GH_ENV` if not set'
        required: false
        type: string
        default: 'testing'
    outputs:
      run_id:
        description: 'Run ID of the workflow to download artifacts from.'
        value: ${{ jobs.build.outputs.run_id }}

jobs:
  build:
    name: Basic TypeScript CI validation
    outputs:
      run_id: ${{ steps.output-run-id.outputs.run_id }}
    environment: ${{ inputs.environment }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['${{ inputs.operating-system }}']
    steps:
      - name: Checkout repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: pnpm setup
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          run_install: false

      - name: Node setup
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version-file: ${{ inputs.node-version-file }}
          cache: ${{ inputs.node-caching }}

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Lint code
        run: pnpm run lint

      - name: Format code
        run: pnpm run format

      - name: Type check
        run: pnpm run typecheck

      - name: Run unit tests
        run: pnpm run test:ci

      - name: Upload code coverage artifact
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build project
        run: pnpm run build --if-present

      - name: Output run ID
        id: output-run-id
        run: echo "::set-output name=run_id::${{ github.run_id }}"

      - name: Archive production artifacts
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 #v4.6.1
        with:
          name: dist_${{ github.run_id }}
          path: dist/*/**

      - name: Archive code coverage results
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 #v4.6.1
        with:
          name: code-coverage_${{ github.run_id }}
          path: dist/test/code-coverage.html
