name: TypeScript CI Workflow Template

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_HUB }}
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  CI: true

jobs:
  basic-check:
    name: Basic Check
    uses: ./.github/workflows/reusable-basic-test.yml

  check-dist:
    needs: [basic-check]
    name: Check transpiled JavaScript
    uses: ./.github/workflows/reusable-check-dist.yml
    with:
      dist-path: 'dist'

  integration-test:
    name: Integration Test
    uses: ./.github/workflows/reusable-testing.yml
