name: TypeScript CI Workflow Template

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

permissions:
  contents: read

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_HUB }}
  # CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  GH_ENV: testing
  CI: true

jobs:
  basic-check:
    name: Basic Check
    uses: ./.github/workflows/basic-test.yml

  check-dist:
    name: Check transpiled JavaScript
    uses: ./.github/workflows/check-dist.yml
    with:
      dist-path: 'dist'

  integration-test:
    name: Integration Test
    uses: ./.github/workflows/testing.yml
